{
  "text-color": "#abb2bf",
  "background-color": "#282c34",
  "line-number-color": "#4b5263",
  "line-number-background-color": "#282c34",
  "text-styles": {
    "Keyword": {
      "text-color": "#c678dd",
      "bold": true
    },
    "String": {
      "text-color": "#98c379"
    },
    "Float": {
      "text-color": "#d19a66"
    },
    "SpecialChar": {
      "text-color": "#98c379"
    },
    "Comment": {
      "text-color": "#5c6370",
      "italic": true
    }
  }
}