title: "Kinetic Equations: Classical Foundations and Modern Computational Perspectives"
date: 2026-07-09
author:
  - Stefano Magrini Alunno
  - Lorenzo Pareschi (Professor of the lecture)
lang: en
categories:
  - phd-lectures

origin: works